const pricingItems = [
    {title: 'Regular',
     icon: "iconRegular",
     smallInfo: "Starter Plan",
     listInfo: [
            { infoName: "Limited Projects"},
            { infoName: "Regular Support Business"},
            { infoName: "P1 month Free Trial"},
            { infoName: "3GB storage"},
            { infoName: "Ads Preview"},
              ],
     smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
     price: "Free",
     time: "For Limited Period",
        },
    {title: 'Platinum',
        icon: "iconPlatinum",
        smallInfo: "For the best results",
        listInfo: [
            { infoName: "Limited Projects"},
            { infoName: "Regular Support Business"},
            { infoName: "P1 month Free Trial"},
            { infoName: "20GB storage"},
            { infoName: "Ads Preview"},
        ],
        smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
        price: "$342",
        time: "For Limited Period",
    },
    {title: 'Standard',
        icon: "iconStandard",
        smallInfo: "Most popular",
        listInfo: [
            { infoName: "Limited Projects"},
            { infoName: "Regular Support Business"},
            { infoName: "P1 month Free Trial"},
            { infoName: "10GB storage"},
            { infoName: "Ads Preview"},
               ],
        smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
        price: "$234",
        time: "Billing Monthly",
    },
];

export default pricingItems