const products = [
    { nameProduct: "product1",
       id:  "product1id",
      moreInfo:
            [
            {title: 'Best in Class for product1',
                icon: "productInfoIcon1",
                smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
            },
            {title: 'Authenticity for product1',
                icon: "productInfoIcon2",
                smallDescription: "Lorem consetetur sadipscing ipsum dolor sit amet, consetetur sadipscing consetetur sadipscing elitr, sed diam nonumy.",
            },
            {title: 'Email Support for product1',
                icon: "productInfoIcon3",
                smallDescription: "Lorem ipsum dolor Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.sit amet, ipsum consetetur sadipscing dolor sit amet ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod.",
            },
            {title: 'Discounts Available for product1 ',
                icon: "productInfoIcon4",
                smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
            },
            {title: 'Powerful Marketing for product1',
                icon: "productInfoIcon5",
                smallDescription: "Lorem consetetur sadipscing ipsum dolor sit amet, consetetur sadipscing consetetur sadipscing elitr, sed diam nonumy.",
            },
            {title: 'Inventory management for product1',
                icon: "productInfoIcon6",
                smallDescription: "Lorem ipsum dolor Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.sit amet, ipsum consetetur sadipscing dolor sit amet ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod.",
            },
        ]},
    {nameProduct: "product2",
        id:  "product2id",
        moreInfo:[
            {title: 'Best in Class for product2',
                icon: "productInfoIcon1",
                smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
            },
            {title: 'Authenticity for product2',
                icon: "productInfoIcon2",
                smallDescription: "Lorem consetetur sadipscing ipsum dolor sit amet, consetetur sadipscing consetetur sadipscing elitr, sed diam nonumy.",
            },
            {title: 'Email Support for product2',
                icon: "productInfoIcon3",
                smallDescription: "Lorem ipsum dolor Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.sit amet, ipsum consetetur sadipscing dolor sit amet ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod.",
            },
            {title: 'Discounts Available for product2',
                icon: "productInfoIcon4",
                smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
            },
            {title: 'Powerful Marketing for product2',
                icon: "productInfoIcon5",
                smallDescription: "Lorem consetetur sadipscing ipsum dolor sit amet, consetetur sadipscing consetetur sadipscing elitr, sed diam nonumy.",
            },
            {title: 'Inventory management for product2',
                icon: "productInfoIcon6",
                smallDescription: "Lorem ipsum dolor Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.sit amet, ipsum consetetur sadipscing dolor sit amet ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod.",
            },
        ]},
    {nameProduct: "product3",
        id:  "product3id",
        moreInfo:[
            {title: 'Best in Class for product3',
                icon: "productInfoIcon1",
                smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
            },
            {title: 'Authenticity for product3',
                icon: "productInfoIcon2",
                smallDescription: "Lorem consetetur sadipscing ipsum dolor sit amet, consetetur sadipscing consetetur sadipscing elitr, sed diam nonumy.",
            },
            {title: 'Email Support for product3',
                icon: "productInfoIcon3",
                smallDescription: "Lorem ipsum dolor Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.sit amet, ipsum consetetur sadipscing dolor sit amet ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod.",
            },
            {title: 'Discounts Available for product3',
                icon: "productInfoIcon4",
                smallDescription: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr.",
            },
            {title: 'Powerful Marketing for product3',
                icon: "productInfoIcon5",
                smallDescription: "Lorem consetetur sadipscing ipsum dolor sit amet, consetetur sadipscing consetetur sadipscing elitr, sed diam nonumy.",
            },
            {title: 'Inventory management for product3',
                icon: "productInfoIcon6",
                smallDescription: "Lorem ipsum dolor Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor.sit amet, ipsum consetetur sadipscing dolor sit amet ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod.",
            },
        ]}
];

export default products